import { AwardCategory, AwardsCategoryNames } from '../types/award-categories';

export const awards: Record<AwardsCategoryNames, AwardCategory> = {
  activity: {
    category: 'activity',
    backgroundIcon: 'triangle',
    backgroundIconType: 'Ionicons',
    backgroundColor: '#D89B7C',
    unit: 'habits',
    currentLevel: 0,
    levels: [
      {
        icon: '☘️',
        name: 'First step',
        level: 1,
        goal: 15,
        shortDescription: 'Completed 15 habits',
        description: 'Successfully completed 15 habits',
        currentProgress: 0,
      },
      {
        icon: '🌱️',
        name: 'Step to success',
        level: 2,
        goal: 40,
        shortDescription: 'Completed 40 habits',
        description: 'Successfully completed 40 habits',
        currentProgress: 0,
      },
      {
        icon: '🌿️',
        name: 'Steady Step',
        level: 3,
        goal: 75,
        shortDescription: 'Completed 75 habits',
        description: 'Successfully completed 75 habits',
        currentProgress: 0,
      },
      {
        icon: '🪴️',
        name: 'Steady Pace',
        level: 4,
        goal: 100,
        shortDescription: 'Completed 100 habits',
        description: 'Successfully completed 100 habits',
        currentProgress: 0,
      },
      {
        icon: '🌳',
        name: 'Mastery Step',
        level: 5,
        goal: 150,
        shortDescription: 'Completed 150 habits',
        description: 'Successfully completed 150 habits',
        currentProgress: 0,
      },
    ],
  },
  all_stream: {
    category: 'all_stream',
    backgroundIcon: 'circle',
    backgroundIconType: 'FontAwesome',
    backgroundColor: '#7FA89A',
    unit: 'days',
    currentLevel: 0,
    levels: [
      {
        icon: '💪️',
        name: 'Consistency',
        level: 1,
        goal: 5,
        shortDescription: '5 consecutive days',
        description: 'Completed all habits for 5 consecutive days',
        currentProgress: 0,
      },
      {
        icon: '🔥',
        name: 'Retention',
        level: 2,
        goal: 15,
        shortDescription: '15 consecutive days',
        description: 'Completed all habits for 15 consecutive days',
        currentProgress: 0,
      },
      {
        icon: '⏳️',
        name: 'Reinforcement',
        level: 3,
        goal: 30,
        shortDescription: '30 consecutive days',
        description: 'Completed all habits for 30 consecutive days',
        currentProgress: 0,
      },
      {
        icon: '🔗️',
        name: 'Sustainability или Stability',
        level: 4,
        goal: 60,
        shortDescription: '60 consecutive days',
        description: 'Completed all habits for 60 consecutive days',
        currentProgress: 0,
      },
      {
        icon: '🏆',
        name: 'Habit Mastery',
        level: 5,
        goal: 90,
        shortDescription: '90 consecutive days',
        description: 'Completed all habits for 90 consecutive days',
        currentProgress: 0,
      },
    ],
  },
  one_stream: {
    category: 'one_stream',
    backgroundIcon: 'square',
    backgroundIconType: 'FontAwesome',
    backgroundColor: '#9A90B8',
    unit: 'days',
    currentLevel: 0,
    levels: [
      {
        icon: '🪓',
        name: 'First Strike',
        level: 1,
        goal: 30,
        shortDescription: '30 consecutive days',
        description: 'Completed at least one habit for 30 consecutive days',
        currentProgress: 0,
      },
      {
        icon: '🎯',
        name: 'Strong Connections',
        level: 2,
        goal: 60,
        shortDescription: '60 consecutive days',
        description: 'Completed at least one habit for 60 consecutive days',
        currentProgress: 0,
      },
      {
        icon: '⚙️️',
        name: 'Unbreakable System',
        level: 3,
        goal: 100,
        shortDescription: '100 consecutive days',
        description: 'Completed at least one habit for 100 consecutive days',
        currentProgress: 0,
      },
      {
        icon: '🛡️️',
        name: 'Habit Armor',
        level: 4,
        goal: 180,
        shortDescription: '180 consecutive days',
        description: 'Completed at least one habit for 180 consecutive days',
        currentProgress: 0,
      },
      {
        icon: '🏋️',
        name: 'Iron Will',
        level: 5,
        goal: 365,
        shortDescription: '365 consecutive days',
        description: 'Completed at least one habit for 365 consecutive days',
        currentProgress: 0,
      },
    ],
  },
  overtop: {
    category: 'overtop',
    backgroundIcon: 'hexagon',
    backgroundIconType: 'MaterialIcons',
    backgroundColor: '#E3B46A',
    unit: 'times',
    currentLevel: 0,
    levels: [
      {
        icon: '🏔️',
        name: 'First Peak',
        level: 1,
        goal: 15,
        shortDescription: 'Exceeded 15 times',
        description: 'Exceed the target 15 times',
        currentProgress: 0,
      },
      {
        icon: '🧗',
        name: 'Confident Climb',
        level: 2,
        goal: 45,
        shortDescription: 'Exceeded 45 times',
        description: 'Exceed the target 45 times',
        currentProgress: 0,
      },
      {
        icon: '🌄️️',
        name: 'High Ascent',
        level: 3,
        goal: 75,
        shortDescription: 'Exceeded 75 times',
        description: 'Exceed the target 75 times',
        currentProgress: 0,
      },
      {
        icon: '🏞️️️',
        name: 'Mountain top',
        level: 4,
        goal: 100,
        shortDescription: 'Exceeded 100 times',
        description: 'Exceed the target 100 times',
        currentProgress: 0,
      },
      {
        icon: '📈️',
        name: 'Habit Everest',
        level: 5,
        goal: 200,
        shortDescription: 'Exceeded 200 times',
        description: 'Exceed the target 200 times',
        currentProgress: 0,
      },
    ],
  },
  time: {
    category: 'time',
    backgroundIcon: 'rhombus',
    backgroundIconType: 'MaterialCommunityIcons',
    backgroundColor: '#5FB3B3',
    unit: 'hours',
    currentLevel: 0,
    levels: [
      {
        icon: '⏰',
        name: 'First Timer',
        level: 1,
        goal: 15,
        shortDescription: '15 Hours Completed',
        description: 'Spent 15 hours building positive habits',
        currentProgress: 0,
      },
      {
        icon: '🔄',
        name: 'Steady Rhythm',
        level: 2,
        goal: 45,
        shortDescription: '45 Hours Completed',
        description: 'Spent 45 hours building positive habits',
        currentProgress: 0,
      },
      {
        icon: '🕰️️️',
        name: 'Hours of Discipline',
        level: 3,
        goal: 75,
        shortDescription: '75 Hours Completed',
        description: 'Spent 75 hours building positive habits',
        currentProgress: 0,
      },
      {
        icon: '📆️️️',
        name: 'Planning Master',
        level: 4,
        goal: 100,
        shortDescription: '100 Hours Completed',
        description: 'Spent 100 hours building positive habits',
        currentProgress: 0,
      },
      {
        icon: '⏱️️',
        name: 'Master of Time',
        level: 5,
        goal: 150,
        shortDescription: '150 Hours Completed',
        description: 'Spent 150 hours building positive habits',
        currentProgress: 0,
      },
    ],
  },
};
